version: '2'
services:
    cornerstonecloudserver-app:
        image: cornerstonecloudserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cornerstonecloudserver-postgresql:5432/CornerstoneCloudServer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cornerstonecloudserver-postgresql:
        extends:
            file: postgresql.yml
            service: cornerstonecloudserver-postgresql
